FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD sh -c "sleep 10 && echo 'Running migrations...' && alembic upgrade head && echo 'Starting API...' && uvicorn app.main:app --host 0.0.0.0 --port 8000"